- README.md
- src/home_robot/home_robot/client/local_hello_robot.py
- src/home_robot_hw/CMakeLists.txt
- src/home_robot_hw/install.md
- src/home_robot_hw/launch/controller.launch
- src/home_robot_hw/launch/home_robot_nodes.launch
- src/home_robot_hw/launch/labeling.launch
- src/home_robot_hw/launch/startup_stretch_hector_slam.launch
- src/home_robot_hw/launch/stretch_hector_mapping.launch
- src/home_robot_hw/launch/visualization.launch
- src/home_robot_hw/package.xml
Add documentation for setting up the codebase on a clean Stretch 2
renamed home_robot ros package to home_robot_hw
added install.md in home_robot_hw
test on real robot
> Installation documentation for home_robot_hw on the real robot

- src/home_robot_hw/install.md
testing push access through my account
> spelling-fix

- src/home_robot/home_robot/control/goto_controller.py
- src/home_robot/setup.py
- src/home_robot_hw/home_robot_hw/nodes/goto_controller.py
- tests/home_robot/control/utils.py
- Remove sophuspy so as to not introduce a hard-to-install dependency into habitat-lab
- Change configuration API for the goto controller to directly accept DictConfigs
- Add a relative goal interface for the goto controller
> Changes for integration into Habitat-Lab

- src/home_robot_hw/install.md
typos missed when merging last PR
typos missed when merging last PR
n/a
> Fix typos in install guide

- README.md
For local network setups which do not have access to internet.
> add instructions to use rsync

- src/home_robot/README.md
Creating env on robot removes important dependencies. This explicitly instructs users to install things on robot natively.
Tested on stretch v2.
> bifurcate server/robot install instructions

- src/home_robot/home_robot/client/local_hello_robot.py
- src/home_robot/home_robot/utils/image.py
- src/home_robot_hw/home_robot_hw/env/stretch_object_nav_env.py
- src/home_robot_hw/home_robot_hw/nodes/goto_controller.py
The current ObjectNav code does not run on Stretch. This PR updates the ObjectNav code path with the latest changes in other parts of the library. 
* Reduce dependence on `import open3d` working
* fix import bug for `PybulletIKSolver`
* comment out joint positions in stretch_object_nav_env.py`
* fix sophus vs. xyt bugs in two places
Tested locally on Stretch RE1
> Update ObjectNav code path

- src/home_robot_hw/home_robot_hw/nodes/goto_controller.py
> Add is_done determined from odom vel

- .pre-commit-config.yaml
- example/build_3d_map.py
- projects/stretch_objectnav/eval_episode.py
- src/home_robot/home_robot/agent/objectnav_agent/objectnav_agent.py
- src/home_robot/home_robot/control/goto_controller.py
- src/home_robot/home_robot/mapping/semantic/categorical_2d_semantic_map_module.py
- src/home_robot/home_robot/mapping/semantic/categorical_2d_semantic_map_state.py
- src/home_robot/home_robot/motion/pinocchio_ik_solver.py
- src/home_robot/home_robot/perception/detection/detic/detic_perception.py
- src/home_robot/home_robot/perception/detection/lseg/modules/lseg_module.py
- src/home_robot/home_robot/perception/detection/lseg/modules/lsegmentation_module.py
- src/home_robot/home_robot/perception/detection/lseg/modules/models/lseg_net.py
- src/home_robot/home_robot/perception/detection/lseg/utils/clip_utils.py
- src/home_robot/home_robot/perception/detection/lseg/utils/models.py
- src/home_robot/home_robot/utils/point_cloud.py
- src/home_robot/home_robot/utils/pose.py
- src/home_robot_hw/home_robot_hw/env/simple_navigation_env.py
- src/home_robot_hw/home_robot_hw/env/stretch_abstract_env.py
- src/home_robot_hw/home_robot_hw/nodes/camera_pose_publisher.py
- src/home_robot_hw/home_robot_hw/nodes/goto_controller.py
- src/home_robot_hw/home_robot_hw/nodes/state_estimator.py
- src/home_robot_hw/home_robot_hw/ros/camera.py
- src/home_robot_hw/home_robot_hw/ros/recorder.py
- src/home_robot_hw/home_robot_hw/ros/stretch_ros.py
- src/home_robot_hw/scripts/interactive_marker.py
- src/home_robot_hw/scripts/run_controller_teleop.py
- src/home_robot_sim/home_robot_sim/env/habitat_abstract_env.py
- tests/home_robot/motion/test_ik.py
We accidentally excluded all files from black and isort by removing excluded directories in #63
This PR reverts the change.
- Fix pre_commit_config.yaml to not exclude everything
- TODO: Run pre-commit and clean up files once outstanding branches are merged.
> Remove accidental precommit exclusions

- .github/PULL_REQUEST_TEMPLATE.md
- tests/hw_manual_test.py
Add a minimal hardware test script.
Future PRs that modify code that is used by the hardware stack should be tested with this script before merging to prevent hardware performance regression.
> Add hardware test script

- projects/collect_h5.py
- projects/stretch_grasping/utils/look_ee.py
- projects/stretch_grasping/utils/look_front.py
- src/home_robot_hw/home_robot_hw/ros/path.py
- src/home_robot_hw/home_robot_hw/teleop/stretch_xbox_controller.py
Fixes import bugs due to moving motion out of agent.
With hw_manual_test script; barring the arm not moving.
> Fixing motion import bugs

- tests/hw_manual_test.py
- Debug arm motion parameters to allow arm to correctly extend
- Added sleep to head motion
- Made printouts more comprehensive
> Debug and tune hardware manual test

- example/basic_robot_control.py
- example/build_3d_map.py
- projects/collect_h5.py
- projects/stretch_grasping/pick_cup_real_robot.py
- src/home_robot/home_robot/motion/stretch.py
- src/home_robot_hw/home_robot_hw/constants.py
- src/home_robot_hw/home_robot_hw/ros/abstract.py
- src/home_robot_hw/home_robot_hw/ros/stretch_ros.py
- src/home_robot_hw/home_robot_hw/stretch_client/api.py
- src/home_robot_hw/home_robot_hw/teleop/stretch_xbox_controller.py
- src/home_robot_hw/scripts/run_controller_teleop.py
- tests/home_robot/motion/test_ik.py
- tests/hw_manual_test.py
> Rename `motion.stretch.HelloStretch` to `motion.stretch.HelloStretchKinematics`

- src/home_robot_hw/home_robot_hw/stretch_client/api.py
- src/home_robot_hw/home_robot_hw/stretch_client/modules/abstract.py
- src/home_robot_hw/home_robot_hw/stretch_client/modules/head.py
- src/home_robot_hw/home_robot_hw/stretch_client/modules/manip.py
- src/home_robot_hw/home_robot_hw/stretch_client/modules/nav.py
> Add wait mechanic for control client modules

- projects/stretch_grasping/build_3d_map.py
- src/home_robot/home_robot/mapping/voxel.py
Store some extra data to make sure that we can capture the 3d info we need for usa-nets/clip-fields.
- info field in sparse voxel map
- pickle function
-
- real robot tests
> Capture 3d data including camera intrinsics over time

- src/home_robot_hw/home_robot_hw/utils/grasping.py
Bug fix
renamed hellostretch to hellostretchkinematics
> Fix hello stretch kinematics inclusion in hw tools

- src/home_robot/home_robot/agent/objectnav_agent/sampling_agent.py
- src/home_robot/home_robot/navigation_planner/rrt.py
Will be an intro point for other types of planner
adding placeholders for alternate motion planner
> Add templates for the sampling-based planning agent

- projects/stretch_grasping/build_3d_map.py
- src/home_robot_hw/home_robot_hw/env/stretch_pick_and_place_env.py
- src/home_robot_hw/home_robot_hw/remote/api.py
- src/home_robot_hw/home_robot_hw/utils/grasping.py
- Set up motion planners
- Test integration
- Config changes and bug fixes
> Bug fixes and code cleanup for OVMM 3d-map example script

- projects/habitat_ovmm/configs/agent/floorplanner_eval.yaml
- projects/stretch_grasping/configs/agent/floorplanner_eval.yaml
- projects/stretch_objectnav/configs/agent/floorplanner_eval.yaml
- src/home_robot/home_robot/agent/objectnav_agent/objectnav_agent_module.py
- src/home_robot/home_robot/mapping/geometric/geometric_map_module.py
- src/home_robot/home_robot/mapping/semantic/categorical_2d_semantic_map_module.py
> Update configs for OVMM sim baseline

- examples/1_hw_basic_control.py
- src/home_robot/home_robot/motion/stretch.py
- src/home_robot_hw/home_robot_hw/remote/api.py
- src/home_robot_hw/home_robot_hw/remote/modules/manip.py
- src/home_robot_hw/home_robot_hw/teleop/keyboard_teleop.py
Was having issues with Pybullet IK where it was unable to solve for valid joint angles on certain occations.
Switching to Pinocchio fixed the problem.
Also fixed a EE pose control bug and added a rotation function which came in handy for testing IK.
- Make Pinocchio the default IK solver
- Fix bug in relative orientation in `StretchClient.manip.goto_ee_pose`
- Add `rotate_ee` method in `StretchClient.manip` for intuitive ee orientation control
- Modify gripper teleop control for easier grasping
Played around with keyboard teleop and the `rotate_ee` API on a Stretch 2 robot.
> Minor fixes for IK

- projects/habitat_ovmm/eval_vectorized.py
- src/home_robot/home_robot/navigation_planner/discrete_planner.py
- src/home_robot_sim/home_robot_sim/env/habitat_objectnav_env/constants.py
- src/home_robot_sim/home_robot_sim/env/habitat_objectnav_env/visualizer.py
- src/home_robot_sim/home_robot_sim/env/habitat_ovmm_env/habitat_ovmm_env.py
- In main, DETIC evaluation works fine but evaluation with GT semantics breaks post recent commit.
- dilate goal before computing distance to goal for `closest_goal_map`
> OVMM: Bug fixes for navigation

- projects/habitat_ovmm/configs/agent/floorplanner_eval.yaml
- src/home_robot/home_robot/mapping/semantic/categorical_2d_semantic_map_module.py
- src/home_robot/home_robot/navigation_planner/discrete_planner.py
> [OVMM] Sim fixes after recent merge

- projects/stretch_ovmm/configs/agent/floorplanner_eval.yaml
- projects/stretch_ovmm/eval_episode.py
- projects/stretch_ovmm/requirements.txt
- src/home_robot/home_robot/agent/ovmm_agent/ppo_agent.py
> dirty commit for sriram

- src/home_robot_hw/launch/rplidar.launch
- src/home_robot_hw/launch/startup_stretch_hector_slam.launch
- sometimes lidar node doesnt start properly
- this prevents it from failing silently
> Add rplidar launch file and make node required

- src/home_robot/config/control/noplan_velocity_hw.yaml
- match simulation, allow for finer-grained control of the robot
- update config file
> Reduce tolerances for robot controller to get more precision

- src/home_robot_hw/launch/startup_stretch_hector_slam.launch
Should improve depth quality and real-world performance; suggested by Santhoth
> add filters to realsense code

- projects/habitat_ovmm/configs/agent/floorplanner_eval.yaml
- src/home_robot/home_robot/agent/ovmm_agent/ovmm_agent.py
- src/home_robot/home_robot/place_policy/heuristic_place_policy.py
- src/home_robot/home_robot/utils/rotation.py
Adds initial, simple version for a rudimentary heuristic place policy.
To test this, please set the following in `projects/habitat_ovmm/configs/agent/floorplanner_eval.yaml`:
```
skip_nav_to_obj: True
skip_nav_to_rec: True
skip_pick: True
skip_place: False
skip_orient_obj: True
```
and set `place_init=True` in `habitat/config/benchmark/rearrange/ovmm.yaml` under `habitat.task`.
> Towards heuristic place support

- src/home_robot/home_robot/agent/ovmm_agent/ovmm_agent.py
> Fixes policy init bug in heuristic place

- src/home_robot/home_robot/place_policy/heuristic_place_policy.py
- src/home_robot_sim/home_robot_sim/env/habitat_ovmm_env/habitat_ovmm_env.py
- Minor bugs while testing integrated pipeline in sim
- Using ContinuousBodyAction for consistency in sim/real api
- Correct return values 
- Using ContinuousBodyAction
> Heuristic place testing

- projects/stretch_ovmm/eval_episode.py
- src/home_robot/home_robot/agent/hierarchical/pick_and_place_agent.py
- src/home_robot/home_robot/manipulation/grasping.py
- src/home_robot/home_robot/motion/stretch.py
- src/home_robot/home_robot/navigation_policy/object_navigation/objectnav_frontier_exploration_policy.py
- src/home_robot/home_robot/place_policy/__init__.py
- src/home_robot_hw/home_robot_hw/env/stretch_pick_and_place_env.py
- src/home_robot_hw/home_robot_hw/utils/grasping.py
- Place experiments on the real robot
- Testing hierarchical policy
- Making sure grasp planner code is clean and easier to use
- Fixed bugs in observation handling
- Update obs handler to make sure its getting goal object
- Correctly search for object on start receptacle in the real world not just any object
> Real-robot place integration

- projects/habitat_ovmm/configs/agent/floorplanner_detic_eval.yaml
- projects/habitat_ovmm/configs/agent/floorplanner_eval.yaml
- src/home_robot/home_robot/agent/ovmm_agent/ovmm_agent.py
- src/home_robot/home_robot/agent/ovmm_agent/ppo_agent.py
- src/home_robot/home_robot/perception/detection/lseg/modules/lsegmentation_module.py
- src/home_robot_hw/home_robot_hw/nodes/contact_graspnet_server.py
- src/home_robot_sim/home_robot_sim/env/habitat_objectnav_env/visualizer.py
- src/home_robot_sim/home_robot_sim/env/habitat_ovmm_env/habitat_ovmm_env.py
> Quick fix - habitat version update, bug fixes, linting

- src/home_robot_hw/home_robot_hw/remote/modules/manip.py
> Added method for reading gripper-state

- .circleci/config.yml
- .gitmodules
- README.md
- src/home_robot_sim/README.md
- src/home_robot_sim/environment.yml
- Update assets link
- Update habitat sim version
- Update habitat-lab commit (now on object_rearrange)
- Update habitat-lab branch to object_rearrange
- Add habitat-sim as submodule
- Update README
> [OVMM] Update sim setup

- src/home_robot/home_robot/control/feedback/velocity_controllers.py
- src/home_robot/home_robot/control/goto_controller.py
- src/home_robot_hw/home_robot_hw/nodes/goto_controller.py
- src/home_robot_hw/launch/mapping_demo.rviz
- add a simple interface to set robot velocities in the home_robot low level controller
- need to also add ROS hooks for messaging
> Add velocity profile information to controller

- projects/habitat_objectnav/README.md
Updates FP v0.2.0 episode dataset link in [README](https://github.com/facebookresearch/home-robot/tree/main/projects/habitat_objectnav).
> Updates FP v0.2.0 episode dataset link in README

- README.md
- src/home_robot_sim/README.md
1. The previous Sim README was unclear.
2. The previous main README file contained redundant and inconsistent instructions for Sim installation.
> Update instructions for sim installation

- src/home_robot/config/control/noplan_velocity_hw.yaml
- src/home_robot/config/control/noplan_velocity_sim.yaml
- src/home_robot/home_robot/control/goto_controller.py
- src/home_robot_hw/home_robot_hw/nodes/goto_controller.py
- add a timeout to the controller
> Timeouts for the robot controller - abandon goals after fixed time window

- README.md
> add competition link to repo

- projects/stretch_ovmm/eval_episode.py
- src/home_robot/home_robot/manipulation/voxel_grasps.py
- src/home_robot_hw/home_robot_hw/env/stretch_pick_and_place_env.py
- src/home_robot_hw/home_robot_hw/utils/grasping.py
- add --visualize-grasps flag to show the mask the grasp code is using
- find the closest mask of the target class instead of just any object
- make sure you always generate grasps when voxelizing - by adding one at the median xyz of the top 10% of points
> Grasp improvements - check proximity and do the dumb thing

- src/home_robot_hw/home_robot_hw/teleop/stretch_xbox_controller.py
Be able to use navigation again after using the position mode.
> Bug-fix for switching b/w manip and nav mode

- projects/habitat_ovmm/configs/agent/floorplanner_eval.yaml
- projects/stretch_ovmm/configs/agent/floorplanner_eval.yaml
- src/home_robot/home_robot/agent/ovmm_agent/ovmm_agent.py
- src/home_robot/home_robot/agent/ovmm_agent/ovmm_perception.py
> Add flag to switch to DETIC visualization

- src/home_robot_hw/home_robot_hw/env/stretch_pick_and_place_env.py
no need to do this extra rotation
> remove rotate in switch to nav mode

- src/home_robot/home_robot/manipulation/grasping.py
add an extra waypoint to avoid going directly to end position
> add extra waypoint to improve pick reliability

- projects/habitat_ovmm/test_rendering.py
> Add script for testing rendering improvements minimally

- src/home_robot/home_robot/manipulation/heuristic_place_policy.py
Unnecessary rotate at the end of the place policy
> Remove navigation mode at end of place policy

- projects/habitat_ovmm/configs/agent/floorplanner_eval.yaml
- projects/habitat_ovmm/configs/agent/nav_to_obj_rl.yaml
> Change RL nav to discrete actions

- projects/stretch_ovmm/eval_episode.py
> Add step limit to eval_episode.py

- README.md
- src/home_robot/home_robot/navigation_planner/discrete_planner.py
- src/home_robot_sim/README.md
- Update habitat-lab and habitat-sim versions
- Add back stopping when nowhere left to explore
- Add RL training instructions to README
Tested with a fresh environment install, tested that the discrete planner change does not affect sim results
> [Ovmm] habitat/readme/planner updates

- .circleci/config.yml
- .gitmodules
- README.md
- docs/install_robot.md
- projects/habitat_ovmm/README.md
- projects/habitat_ovmm/eval_dataset.py
- src/home_robot/environment.yml
- src/home_robot/home_robot/perception/detection/lseg/modules/lsegmentation_module.py
- src/home_robot/requirements.txt
- src/home_robot/setup.py
- src/home_robot_hw/home_robot_hw/nodes/contact_graspnet_server.py
- src/home_robot_sim/README.md
- src/home_robot_sim/environment.yml
- src/home_robot_sim/home_robot_sim/env/habitat_objectnav_env/visualizer.py
> [Ovmm] Update habitat-lab, habitat-sim and README

- .gitmodules
- projects/habitat_ovmm/configs/agent/hssd_eval.yaml
> link to public repo for scenes 

- README.md
- src/home_robot_sim/README.md
Recommended practice to use python -m instead of just pip
call conda before running these commands
> Minor tweaks to installation guide

- src/home_robot/home_robot/manipulation/grasping.py
- src/home_robot/home_robot/motion/stretch.py
- src/home_robot_hw/home_robot_hw/env/stretch_pick_and_place_env.py
Bug in error checking meant that we could never grasp objects > 1 meter off the ground; this fixes it.
> Fix a minor grasping bug that would make it impossible to grasp objects over 1 meter

- README.md
- projects/habitat_ovmm/README.md
- projects/habitat_ovmm/configs/agent/hssd_eval.yaml
- projects/real_world_ovmm/configs/agent/eval.yaml
- src/home_robot_sim/environment.yml
> Update links to trained ckpts, install hab-sim withbullet

- projects/habitat_ovmm/README.md
- Add git lfs install
- Add fallback for old git version users
> Update dataset clone instructions

- .gitmodules
> Update .gitmodules to use https

- README.md
- docs/network.md
- src/home_robot/requirements.txt
- src/home_robot_hw/environment.yml
Clarifying README and docs for realworld deployment. See exhaustive list of issues here: https://fb.workplace.com/notes/161926060225220/
- Alternate network setups
- Hotspot on robot
- Tailscale
- Hardware Testing throws pybullet.error
- Do git submodule update before hardware test
- Section 5, DETIC formatting bug
- no module named mss
Dependency updates: tested on Stretch RE2-2043
> Realworld readme update

- tests/hw_manual_test.py
Manual test was failing because now our "primitive" motions time out.
Send orientation commands multiple times
> Update the manual test script

- .gitmodules
- src/home_robot/home_robot/agent/exploration_agent/exploration_agent.py
- src/home_robot_hw/home_robot_hw/constants.py
- src/home_robot_hw/home_robot_hw/env/stretch_exploration_env.py
- src/home_robot_hw/home_robot_hw/env/stretch_pick_and_place_env.py
stretch_exploration does not work in real, several variable names are assigned to the wrong classes.
- self.get_base_pose -> self.robot.get_base_pose
- self.goto -> self.robot.nav._ ros_client.goto
- self.get_images -> self.robot.head.get_images
- self.in_navigation_mode -> self.robot.in_navigation_mode
Tested on robot with @MatthewChang, `projects/stretch_exploration/eval_episode.py` moves the robot in real and builds a semantic map. Does not explore as intended, though.
> exploration env bug fixes; robot now moves

- projects/instanceimagenav/README.md
- projects/instanceimagenav/configs/instance_imagenav_hm3d.yaml
- src/home_robot/home_robot/agent/imagenav_agent/imagenav_agent.py
- src/home_robot/home_robot/agent/imagenav_agent/visualizer.py
Since ImageNav was added to Home-Robot (#87), the `Categorical2DSemanticMapModule` and `DiscretePlanner` have received breaking changes. Resulting API issues pertaining to ImageNav were cataloged in issue #182. This PR aims to restore the functionality of the ImageNav project by fixing these API issues.
Missing config and API entries have been added to restore the functionality of the ImageNav demo. Values were chosen to maintain alignment with the ObjectNav project's use of mapping + planning.
I was able to successfully run the simulation demo:
```bash
cd projects/instanceimagenav
python eval_episode_habitat.py
```
> ImageNav API Fixes

- projects/habitat_ovmm/evaluator.py
- src/home_robot/home_robot/agent/ovmm_agent/ovmm_agent.py
- src/home_robot/home_robot/agent/ovmm_agent/random_agent.py
Refactor: [Remove episode argument in agent reset](https://github.com/facebookresearch/home-robot/pull/285)
> Refactor: Remove episode argument in agent reset

- docs/challenge.md
> Updated challenge readme

- projects/habitat_ovmm/configs/env/hssd_demo.yaml
- projects/habitat_ovmm/configs/env/hssd_eval.yaml
- Update discrete timestep for evaluation (10 degrees would be very less for real-world eval)
- Update default rendering flag
> update discrete step, rendering for eval

- projects/habitat_ovmm/README.md
- projects/habitat_ovmm/install.sh
> Automatic install script for downloading data

- docs/challenge.md
> Fix a broken readme link in the docs

- projects/instanceimagenav/eval_episode_stretch.py
- projects/real_world_ovmm/eval_episode.py
- projects/real_world_ovmm/tests/test_heuristic_policies.py
- projects/slap_manipulation/scripts/edit_demonstrations.py
- projects/stretch_objectnav/rotate_in_place.py
- src/home_robot/home_robot/agent/ovmm_agent/ovmm_llm_agent.py
- src/home_robot/home_robot/mapping/semantic/instance_tracking_modules.py
- src/home_robot_hw/home_robot_hw/nodes/clock.py
> Fix license headers

- README.md
> Minor readme fixes missed in the last PR

- projects/spot/configs/config.yaml
- projects/spot/objectnav.py
- projects/spot/offline_mapping.py
- src/home_robot/home_robot/agent/goat_agent/goat_matching.py
- src/home_robot/home_robot/mapping/semantic/categorical_2d_semantic_map_module.py
- src/home_robot/home_robot/mapping/semantic/instance_tracking_modules.py
> Instance matching for language goals

- src/home_robot/home_robot/mapping/semantic/instance_tracking_modules.py
- src/home_robot/home_robot/navigation_planner/fmm_planner.py
> Instance memory fixes

- docs/challenge.md
Add specific submission commands for the challenge to the doc
> Add specific phase commands since they are misleading

- src/home_robot/home_robot/agent/ovmm_agent/ovmm_perception.py
> Fix bug with agent evaluation

- README.md
Make it harder to miss python3.9 when installing from scratch
> Extra note about python

- README.md
- install_deps.sh
- src/home_robot/home_robot/perception/detection/README.md
Adds basic instructions for Grounded MobileSAM
> add README for installing perception modules

- src/home_robot_sim/home_robot_sim/env/habitat_ovmm_env/habitat_ovmm_env.py
> minor fix when info is None

- docs/install_robot.md
- src/home_robot_hw/home_robot_hw/remote/ros.py
- check if robot is homed
- check if robot is estopped
This should reduce time taken when running experiments (like for competition)
> Add quality of life checks to make sure robots are homed and initalized right

- projects/offline_mapping/build_map.py
- src/home_robot/home_robot/agent/objectnav_agent/objectnav_agent.py
- src/home_robot/home_robot/agent/objectnav_agent/objectnav_agent_module.py
- src/home_robot/home_robot/mapping/semantic/categorical_2d_semantic_map_module.py
- src/home_robot/home_robot/mapping/semantic/instance_tracking_modules.py
> Instance association using IoU of 3d bounding boxes

- .gitmodules
A category was missing in the mapping stored in the updated val episodes, causing crashes.
> Updated category mapping in episodes

- src/home_robot/home_robot/agent/goat_agent/goat_agent.py
- src/home_robot/home_robot/agent/goat_agent/goat_matching.py
Set options for instance aggregation from configs.
> fix defaults for instance clustering

- src/home_robot/home_robot/perception/encoders/__init__.py
- src/home_robot/home_robot/perception/encoders/clip_encoder.py
- src/home_robot/home_robot/perception/encoders/mtm_encoder.py
> Mtm encoder

- src/home_robot_hw/home_robot_hw/remote/modules/manip.py
- src/home_robot_hw/home_robot_hw/remote/ros.py
> velocity control fixes

- src/home_robot/home_robot/agent/multitask/openai_client.py
> add simple openai client

- docs/troubleshooting.md
Add some debugging support for common bugs faced during installation
- [X ] Docs change
- [ X] I have made changes to existing documentation where needed.
- [ X] I have added tests that show that the PR is functional.
- [ X] I ran `tests/hw_manual_test.py` on hardware and observed that robot behavior looks normal.
> update troubleshooting readme
